### ISSUE TITLE
Config isn't working

### ISSUE THREAD

**Issue by spartokos99** [avitran0/deadlocked#66]
Hello,

since the last update my configuration file is not working. I see the file in the new configuration menu, but it doesn't matter if I choose my existing config or create a new one - config doesn't get loaded or saved. Have to re-config all settings every time I start the app.

**Comment by avitran0** [comment]
should be fixed now, please try.

**Comment by nbartokos** [comment]
Still have some issues.

The config doesn't load when I start the app. If I do some changes, switch to config "test" and then back to my default, the settings are saved temporary. When I restart the app the config is still gone/doesn't load from file.

I made a short screen record to understand my problem: https://streamable.com/gy5j36 (online for 2 days on this site).

**Comment by spartokos99** [comment]
Still the same error after the newest commit

**Comment by avitran0** [comment]
debugging with an ide would be great, if not, i can take a look at it tonight. you can add me on discord.

**Comment by spartokos99** [comment]
I'll try it. What's your discord name? Same as here?

**Comment by avitran0** [comment]
avitrano
